In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
b = np.array([2,2,2])
c = np.array([3,1,1])

In [3]:
matrix = np.column_stack((a,b,c))

In [4]:
print(matrix)

[[1 2 3]
 [2 2 1]
 [3 2 1]]


In [5]:
print(type(matrix))

<class 'numpy.ndarray'>


In [6]:
# It is worth noticing that we used column_stack() here to ensure that the vectors are vertical 
# and placed side-by-side to form a matrix. Without the column_stack() function, 
# the vectors will be made horizontal and stacked on top of one another

matrix2 = np.array([a,b,c])
print(matrix2)

[[1 2 3]
 [2 2 2]
 [3 1 1]]


In [7]:
# In NumPy, we can multiply matrices with the dot() function

A = np.array([[2,3],[4,2],[2,2]])
B = np.array([[4,2],[4,6]])

x = np.dot(A,B)
print(x)

[[20 22]
 [24 20]
 [16 16]]


In [8]:
# Since matrix multiplication is defined in terms of scalar products, 
# the matrix product AB exists only if A has as many columns as B has rows. 
# It's useful to remember this shorthand: (m × n) × (n × p) = (m × p) 
# which means that an (m × n) matrix multiplied by an (n × p) matrix yields an (m × p) matrix.

In [9]:
# Reversing the order of multiplication results in an error since B does not have as many columns as A has rows

x = np.dot(B,A)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [10]:
# A natrual consequence of this fact is that matrix multiplication is not commutative. 
# In other words, AB≠BA in general.

In [11]:
# Inverse matrices are computed using the Gauss-Jordan method. In NumPy, we use the linalg.inv() function to do it:

In [12]:
print(matrix)
print('\n-------------------------\n')
print(np.linalg.inv(matrix))

[[1 2 3]
 [2 2 1]
 [3 2 1]]

-------------------------

[[ 3.70074342e-17 -1.00000000e+00  1.00000000e+00]
 [-2.50000000e-01  2.00000000e+00 -1.25000000e+00]
 [ 5.00000000e-01 -1.00000000e+00  5.00000000e-01]]


In [13]:
inverse = np.linalg.inv(matrix)
print(np.dot(matrix, inverse))
print('\n-------------------------\n')
print(np.dot(inverse,matrix))

[[ 1.00000000e+00 -6.66133815e-16  3.33066907e-16]
 [ 0.00000000e+00  1.00000000e+00  1.11022302e-16]
 [ 0.00000000e+00 -2.22044605e-16  1.00000000e+00]]

-------------------------

[[ 1.00000000e+00  0.00000000e+00  1.11022302e-16]
 [ 0.00000000e+00  1.00000000e+00 -4.44089210e-16]
 [-1.11022302e-16  0.00000000e+00  1.00000000e+00]]


In [14]:
singular = np.array([[1,2,3],[1,2,3],[3,3,3]])

In [15]:
inv = np.linalg.inv(singular)

LinAlgError: Singular matrix

In [16]:
# Linear Equations

A = np.array([[2,1,-1],[-3,-1,2],[-2,1,2]])
b = np.array([[8],[-11],[-3]])
inv_A = np.linalg.inv(A)
print(np.dot(inv_A, b))

[[ 2.]
 [ 3.]
 [-1.]]


In [17]:
# The solution is x = 2, y = 3, z = −1. 
# However, computing the inverse matrix is not recommended, 
# since it is numerically unstable i.e. small rounding errors can dramatically affect the result.

# Instead, NumPy solves linear equations by LU decomposition:

In [18]:
print(np.linalg.solve(A, b))

[[ 2.]
 [ 3.]
 [-1.]]


In [19]:
# Of course, we get the same solution. We can check the correctness of the solution by 
# substituting x, y and z into the linear equations.